### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by szlin** [linux-taiwan/www.debian.org.tw#11]
- [ ] Replace the logo of Debian 8 to Debian 10 - @moonape1226
- [ ] Update "新手上路" page @szlin 
- [ ] Update News page - @evshary 
- [ ] Update Join Us page - @moonape1226

**Comment by evshary** [comment]
I can update News page, but we need to check what kind of new we want to post.
Maybe I can just use [the news from official site](https://www.debian.org/News/).
